FROM openjdk:11

EXPOSE 8081

COPY /build/libs/spring-app-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["java","-jar","app.jar"]

# FROM openjdk:11

# EXPOSE 8081

# COPY /build/libs/spring-app-0.0.1-SNAPSHOT.jar app.jar

# CMD ["java","-jar","app.jar"]